### ISSUE TITLE
Two ValueError: invalid literal for int() with base 10: 'False', could not convert string to float: 'False'

### ISSUE THREAD

**Issue by SaraAlthubaiti** [spiralgenetics/truvari#29]
Hi all,

I'm trying to run this comparison command:

`truvari -b NA12878.sorted.vcf -c sorted.vcf.gz --pctsim=0 -o compare_dir/`

But it gives me this error:
```
Traceback (most recent call last):
  File "/anaconda3/lib/python3.7/site-packages/vcf/parser.py", line 390, in _parse_info
    val = self._map(int, vals)
  File "/anaconda3/lib/python3.7/site-packages/vcf/parser.py", line 360, in _map
    for x in iterable]
  File "/anaconda3/lib/python3.7/site-packages/vcf/parser.py", line 360, in <listcomp>
    for x in iterable]
ValueError: invalid literal for int() with base 10: 'False'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/bin/truvari", line 1047, in <module>
    run(sys.argv[1:])
  File "/anaconda3/bin/truvari", line 742, in run
    for entry in regions.iterate(vcf_base):
  File "/anaconda3/bin/truvari", line 545, in iterate
    for entry in vcf_file:
  File "/anaconda3/lib/python3.7/site-packages/vcf/parser.py", line 572, in __next__
    info = self._parse_info(row[7])
  File "/anaconda3/lib/python3.7/site-packages/vcf/parser.py", line 394, in _parse_info
    val = self._map(float, vals)
  File "/anaconda3/lib/python3.7/site-packages/vcf/parser.py", line 360, in _map
    for x in iterable]
  File "/anaconda3/lib/python3.7/site-packages/vcf/parser.py", line 360, in <listcomp>
    for x in iterable]
ValueError: could not convert string to float: 'False'
```
Any help/suggest to solve that please?

**Comment by ACEnglish** [comment]
Please check the INFO field headers in your vcfs. One of your entries has `INFOTAG=False`, but your header defines `##INFO=<ID=INFOTAG, Type=Integer...`. Where **INFOTAG** is one of your info fields.

**Comment by SaraAlthubaiti** [comment]
What I found is some entries have X=False, but X not exist in the header! 

So, I filter those entries and it works now!

Thanks for the help
