### ISSUE TITLE
AttributeError: 'IntervalTree' object has no attribute 'search'

### ISSUE THREAD

**Issue by johnemajor** [spiralgenetics/truvari#36]
Hello, I am using truvari installed via bioconda.  I have tried running the simple quick start script on VCF files produced by CNVnator as well as the reference CNV call set released for NA24385.  Both tests were comparing the same file to itself just to make sure things worked, but all attempts to run truvari yield this stacktrace with the same error:

(wgspy3) jmajor@research-team-one:~/data/CNVitaeTest/NA24385/output$ truvari -b ~/wgs_resources/data/reference/controls/b37/controls/cnv/NA24385/giab/NA24385.cnv.vcf.gz -c ~/wgs_resources/data/reference/controls/b37/controls/cnv/NA24385/giab/NA24385.cnv.vcf.gz -f ~/wgs_resources/data/reference/human/human_g1k_v37_modified.fasta/human_g1k_v37_modified.fasta -o ./OUT
2019-11-23 11:14:48,643 [INFO] Running /locus/home/jmajor/conda/envs/wgspy3/bin/truvari -b /locus/home/jmajor/wgs_resources/data/reference/controls/b37/controls/cnv/NA24385/giab/NA24385.cnv.vcf.gz -c /locus/home/jmajor/wgs_resources/data/reference/controls/b37/controls/cnv/NA24385/giab/NA24385.cnv.vcf.gz -f /locus/home/jmajor/wgs_resources/data/reference/human/human_g1k_v37_modified.fasta/human_g1k_v37_modified.fasta -o ./OUT
2019-11-23 11:14:48,644 [INFO] Params:
{
    "pctovl": 0.0, 
    "sizemax": 50000, 
    "includebed": null, 
    "sizefilt": 30, 
    "cSample": null, 
    "reference": "/locus/home/jmajor/wgs_resources/data/reference/human/human_g1k_v37_modified.fasta/human_g1k_v37_modified.fasta", 
    "no_ref": false, 
    "multimatch": false, 
    "comp": "/locus/home/jmajor/wgs_resources/data/reference/controls/b37/controls/cnv/NA24385/giab/NA24385.cnv.vcf.gz", 
    "typeignore": false, 
    "refdist": 500, 
    "pctsize": 0.7, 
    "passonly": false, 
    "base": "/locus/home/jmajor/wgs_resources/data/reference/controls/b37/controls/cnv/NA24385/giab/NA24385.cnv.vcf.gz", 
    "pctsim": 0.7, 
    "gtcomp": false, 
    "giabreport": false, 
    "debug": false, 
    "output": "./OUT", 
    "bSample": null, 
    "sizemin": 50
}
2019-11-23 11:14:48,654 [INFO] Creating call interval tree for overlap search
2019-11-23 11:15:03,429 [INFO] 74012 call variants
2019-11-23 11:15:03,429 [INFO] 45753 call variants within size range (30, 50000)
Traceback (most recent call last):
  File "/locus/home/jmajor/conda/envs/wgspy3/bin/truvari", line 990, in <module>
    run(sys.argv[1:])
  File "/locus/home/jmajor/conda/envs/wgspy3/bin/truvari", line 739, in run
    for entry in regions.iterate(vcf_base):
  File "/locus/home/jmajor/conda/envs/wgspy3/bin/truvari", line 555, in iterate
    if self.include(entry):
  File "/locus/home/jmajor/conda/envs/wgspy3/bin/truvari", line 567, in include
    return overlaps and len(self.tree[entry.CHROM].search(astart, aend)) == 1
AttributeError: 'IntervalTree' object has no attribute 'search'

I'm eager to get truvari working as it looks like the exact tool for CNV comparison I've been dreading writing myself :-) . I'll poke around and see if I can get more info, but in the meantime, any info on this bug is most welcome.

**Comment by johnemajor** [comment]
pip install intervaltree==2.1.0  fixed this.

**Comment by johnemajor** [comment]
sorted out the fix
