### ISSUE TITLE
TypeError: values expected to be 1-tuple, given len=2

### ISSUE THREAD

**Issue by Tintest** [spiralgenetics/truvari#43]
Hello, I'm having some issues on truvari 1.3.4 and 1.3.2, but not on 1.2

```
truvari -b HG002_SVs_Tier1_v0.6.vcf.gz -c NIST-002_merged_minimap2_ont_s2_sorted.vcf.gz -o Test_ont -r 2000 --pctsim 0 --passonly --includebed HG002_SVs_Tier1_v0.6.bed
2019-12-26 18:46:36,382 [INFO] Running /home/tintest/miniconda3/bin/truvari -b HG002_SVs_Tier1_v0.6.vcf.gz -c NIST-002_merged_minimap2_ont_s2_sorted.vcf.gz -o Test_ont -r 2000 --pctsim 0 --passonly --includebed HG002_SVs_Tier1_v0
.6.bed
2019-12-26 18:46:36,383 [INFO] Params:
{
    "base": "HG002_SVs_Tier1_v0.6.vcf.gz",
    "comp": "NIST-002_merged_minimap2_ont_s2_sorted.vcf.gz",
    "output": "Test_ont",
    "reference": null,
    "giabreport": false,
    "debug": false,
    "prog": false,
    "refdist": 2000,
    "pctsim": 0.0,
    "pctsize": 0.7,
    "pctovl": 0.0,
    "typeignore": false,
    "gtcomp": false,
    "bSample": null,
    "cSample": null,
    "sizemin": 50,
    "sizefilt": 30,
    "sizemax": 50000,
    "passonly": true,
    "no_ref": false,
    "includebed": "HG002_SVs_Tier1_v0.6.bed",
    "multimatch": false
}
[W::hts_idx_load2] The index file is older than the data file: HG002_SVs_Tier1_v0.6.vcf.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: HG002_SVs_Tier1_v0.6.vcf.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: NIST-002_merged_minimap2_ont_s2_sorted.vcf.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: NIST-002_merged_minimap2_ont_s2_sorted.vcf.gz.tbi
2019-12-26 18:46:37,234 [INFO] Including 34830 bed regions
2019-12-26 18:46:37,234 [INFO] Creating call interval tree for overlap search
2019-12-26 18:58:31,367 [INFO] 14398 call variants in total
2019-12-26 18:58:31,367 [INFO] 12793 call variants within size range (30, 50000)
[W::hts_idx_load2] The index file is older than the data file: HG002_SVs_Tier1_v0.6.vcf.gz.tbi
[W::hts_idx_load2] The index file is older than the data file: HG002_SVs_Tier1_v0.6.vcf.gz.tbi
2019-12-26 18:58:31,391 [INFO] Matching base to calls
Traceback (most recent call last):
  File "/home/tintest/miniconda3/bin/truvari", line 1051, in <module>
    main(sys.argv[1:])
  File "/home/tintest/miniconda3/bin/truvari", line 937, in main
    match_entry = copy_entry(match_entry, n_comp_header)
  File "/home/tintest/miniconda3/bin/truvari", line 663, in copy_entry
    info=entry.info)
  File "pysam/libcbcf.pyx", line 2080, in pysam.libcbcf.VariantHeader.new_record
  File "pysam/libcbcf.pyx", line 2746, in pysam.libcbcf.VariantRecordInfo.update
  File "pysam/libcbcf.pyx", line 2569, in pysam.libcbcf.VariantRecordInfo.__setitem__
  File "pysam/libcbcf.pyx", line 683, in pysam.libcbcf.bcf_info_set_value
  File "pysam/libcbcf.pyx", line 579, in pysam.libcbcf.bcf_check_values
TypeError: values expected to be 1-tuple, given len=2
```

Do you know what this may be due to ?

Thank you, regards.

**Comment by ACEnglish** [comment]
Could you provide an example VCF so I can replicate the error? My suspicion
is there's a discrepancy between the vcf header and the info fields such
that the header declares a different 'Number' than what is seen in the
entries.

**Comment by Tintest** [comment]
Here is the .vcf files : https://filesender.renater.fr/?s=download&token=23cade46-a550-7734-50f4-700aa429ee85

I think you are right, but, why is it working in 1.2 and not with the following versions ?

Is there big differences between 1.2 and the followings ?

Thank you, regards.

**Comment by ACEnglish** [comment]
1.2 changed VCF reader libraries. pyvcf was the previous lib, pysam was moved to due to it being faster and stricter adherence to the VCF specification.

It appears that the "SUPTYPE" Header is incorrect at least for the entry at position `1:1223923`.
Header defines` Number=A`, and that line shows `SUPTYPE=AL,SR`.
Changing the header line as shown below fixes the VCF.
```
##INFO=<ID=SUPTYPE,Number=.,Type=String,Description="Type by which the variant is supported.(SR,ALN,NR)">
```
