### ISSUE TITLE
KeyError: 'Illcalls'

### ISSUE THREAD

**Issue by AYYYang** [spiralgenetics/truvari#50]
Hi,

I have ran some commands and the summary.txt and other files were generated, but I had trouble generating the giabreport. Tracing back to the error, I tried printing out the fn by calling```print(fn)``` and the array was printed. However, there was no *call keys found in this array. Could you let me know what I am missing?

```
2020-06-17 02:12:32,796 [WARNING] Excluding 59 contigs present in comparison calls header but not base calls.
2020-06-17 02:12:32,797 [INFO] Creating call interval tree for overlap search
2020-06-17 02:12:32,798 [INFO] 1 call variants in total
2020-06-17 02:12:32,798 [INFO] 1 call variants within size range (30, 50000)
2020-06-17 02:12:32,800 [INFO] Matching base to calls
2020-06-17 02:12:32,802 [WARNING] No TP or FP calls in base!
2020-06-17 02:12:32,802 [INFO] Parsing FPs from calls
2020-06-17 02:12:32,861 [INFO] Stats: {
    "TP-base": 0,
    "TP-call": 0,
    "FP": 1,
    "FN": 20,
    "precision": 0,
    "recall": 0,
    "f1": "NaN",
    "base cnt": 20,
    "call cnt": 1,
    "base size filtered": 2,
    "call size filtered": 0,
    "base gt filtered": 0,
    "call gt filtered": 0,
    "TP-call_TP-gt": 0,
    "TP-call_FP-gt": 0,
    "TP-base_TP-gt": 0,
    "TP-base_FP-gt": 0,
    "gt_precision": 0,
    "gt_recall": 0,
    "gt_f1": "NaN"
}
2020-06-17 02:12:32,861 [INFO] Creating GIAB report
[{'SVTYPE': 'DUP', 'SVMETHOD': 'CNVar', 'LEN': '34572', 'VARIANT': 'esv3637537.fa', 'NumNeighbors': 0, 'NumThresholdNeighbors': 0, 'SAMPLE_GT': '0/1', 'CHROM': '16', 'POS': 115679, 'ID': '91', 'FILTER': '', 'QUAL': None}, {'SVTYPE': 'DUP', 'SVMETHOD': 'CNVar', 'LEN': '34572', 'VARIANT': 'esv3637540.fa', 'NumNeighbors': 0, 'NumThresholdNeighbors': 0, 'SAMPLE_GT': '0/1', 'CHROM': '16', 'POS': 162127, 'ID': '94', 'FILTER': '', 'QUAL': None}, {'SVTYPE': 'DEL', 'SVMETHOD': 'CNVar', 'LEN': '34572', 'VARIANT': 'esv3637541.fa', 'NumNeighbors': 0, 'NumThresholdNeighbors': 0, 'SAMPLE_GT': '0/1', 'CHROM': '16', 'POS': 192277, 'ID': '125', 'FILTER': '', 'QUAL': None}, {'SVTYPE': 'DEL', 'SVMETHOD': 'CNVar', 'LEN': '34572', 'VARIANT': 'esv3637543.fa', 'NumNeighbors': 0, 'NumThresholdNeighbors': 0, 'SAMPLE_GT': '0/1', 'CHROM': '16', 'POS': 196434, 'ID': '96', 'FILTER': '', 'QUAL': None}, {'SVTYPE': 'DEL', 'SVMETHOD': 'CNVar', 'LEN': '34572', 'VARIANT': 'alpha27.6.fa', 'NumNeighbors': 0, 'NumThresholdNeighbors': 0, 'SAMPLE_GT': '0/1', 'CHROM': '16', 'POS': 198215, 'ID': '215', 'FILTER': '', 'QUAL': None}, {'SVTYPE': 'DEL', 'SVMETHOD': 'CNVar', 'LEN': '34572', 'VARIANT': 'THAI.fa', 'NumNeighbors': 0, 'NumThresholdNeighbors': 0, 'SAMPLE_GT': '0/1', 'CHROM': '16', 'POS': 199800, 'ID': '202', 'FILTER': '', 'QUAL': None}, {'SVTYPE': 'DUP', 'SVMETHOD': 'CNVar', 'LEN': '34572', 'VARIANT': 'anti11.fa', 'NumNeighbors': 0, 'NumThresholdNeighbors': 0, 'SAMPLE_GT': '0/1', 'CHROM': '16', 'POS': 203016, 'ID': '3', 'FILTER': '', 'QUAL': None}, {'SVTYPE': 'DEL', 'SVMETHOD': 'CNVar', 'LEN': '34572', 'VARIANT': 'alpha11.fa', 'NumNeighbors': 0, 'NumThresholdNeighbors': 0, 'SAMPLE_GT': '0/1', 'CHROM': '16', 'POS': 203016, 'ID': '4', 'FILTER': '', 'QUAL': None}, {'SVTYPE': 'DEL', 'SVMETHOD': 'CNVar', 'LEN': '34572', 'VARIANT': 'alpha21.9.fa', 'NumNeighbors': 0, 'NumThresholdNeighbors': 0, 'SAMPLE_GT': '0/1', 'CHROM': '16', 'POS': 203509, 'ID': '134', 'FILTER': '', 'QUAL': None}, {'SVTYPE': 'DUP', 'SVMETHOD': 'CNVar', 'LEN': '34572', 'VARIANT': 'anti20.9.fa', 'NumNeighbors': 0, 'NumThresholdNeighbors': 0, 'SAMPLE_GT': '0/1', 'CHROM': '16', 'POS': 215144, 'ID': '9', 'FILTER': '', 'QUAL': None}, {'SVTYPE': 'DEL', 'SVMETHOD': 'CNVar', 'LEN': '34572', 'VARIANT': '16.sea.fa', 'NumNeighbors': 0, 'NumThresholdNeighbors': 0, 'SAMPLE_GT': '0/1', 'CHROM': '16', 'POS': 215400, 'ID': '8', 'FILTER': '', 'QUAL': None}, {'SVTYPE': 'DEL', 'SVMETHOD': 'CNVar', 'LEN': '34572', 'VARIANT': 'alpha4.2.fa', 'NumNeighbors': 0, 'NumThresholdNeighbors': 0, 'SAMPLE_GT': '0/1', 'CHROM': '16', 'POS': 219817, 'ID': '5', 'FILTER': '', 'QUAL': None}, {'SVTYPE': 'DUP', 'SVMETHOD': 'CNVar', 'LEN': '34572', 'VARIANT': 'anti4.2.fa', 'NumNeighbors': 0, 'NumThresholdNeighbors': 0, 'SAMPLE_GT': '0/1', 'CHROM': '16', 'POS': 219817, 'ID': '6', 'FILTER': '', 'QUAL': None}, {'SVTYPE': 'DEL', 'SVMETHOD': 'CNVar', 'LEN': '34572', 'VARIANT': 'alpha30.8.fa', 'NumNeighbors': 0, 'NumThresholdNeighbors': 0, 'SAMPLE_GT': '0/1', 'CHROM': '16', 'POS': 221260, 'ID': '210', 'FILTER': '', 'QUAL': None}, {'SVTYPE': 'DEL', 'SVMETHOD': 'CNVar', 'LEN': '34572', 'VARIANT': 'alpha3.7.fa', 'NumNeighbors': 0, 'NumThresholdNeighbors': 0, 'SAMPLE_GT': '0/1', 'CHROM': '16', 'POS': 223300, 'ID': '1', 'FILTER': '', 'QUAL': None}, {'SVTYPE': 'DUP', 'SVMETHOD': 'CNVar', 'LEN': '34572', 'VARIANT': 'anti3.7.fa', 'NumNeighbors': 0, 'NumThresholdNeighbors': 0, 'SAMPLE_GT': '0/1', 'CHROM': '16', 'POS': 223300, 'ID': '2', 'FILTER': '', 'QUAL': None}, {'SVTYPE': 'DEL', 'SVMETHOD': 'CNVar', 'LEN': '34572', 'VARIANT': 'alpha2.7.fa', 'NumNeighbors': 0, 'NumThresholdNeighbors': 0, 'SAMPLE_GT': '0/1', 'CHROM': '16', 'POS': 225800, 'ID': '21', 'FILTER': '', 'QUAL': None}, {'SVTYPE': 'DEL', 'SVMETHOD': 'CNVar', 'LEN': '34572', 'VARIANT': 'alpha2.4.fa', 'NumNeighbors': 0, 'NumThresholdNeighbors': 0, 'SAMPLE_GT': '0/1', 'CHROM': '16', 'POS': 225996, 'ID': '15', 'FILTER': '', 'QUAL': None}, {'SVTYPE': 'DEL', 'SVMETHOD': 'CNVar', 'LEN': '34572', 'VARIANT': 'alpha1.2.fa', 'NumNeighbors': 0, 'NumThresholdNeighbors': 0, 'SAMPLE_GT': '0/1', 'CHROM': '16', 'POS': 227121, 'ID': '16', 'FILTER': '', 'QUAL': None}, {'SVTYPE': 'DEL', 'SVMETHOD': 'CNVar', 'LEN': '34572', 'VARIANT': 'esv3637554.fa', 'NumNeighbors': 0, 'NumThresholdNeighbors': 0, 'SAMPLE_GT': '0/1', 'CHROM': '16', 'POS': 248243, 'ID': '99', 'FILTER': '', 'QUAL': None}]
Traceback (most recent call last):
  File "/root/miniconda3/bin/truvari", line 1051, in <module>
    main(sys.argv[1:])
  File "/root/miniconda3/bin/truvari", line 1045, in main
    make_giabreport(args, stats_box)
  File "/root/miniconda3/bin/truvari", line 422, in make_giabreport
    collapse_techs(fn)
  File "/root/miniconda3/bin/truvari", line 409, in collapse_techs
    if d[i] > 0:
KeyError: 'Illcalls'
```

**Comment by ACEnglish** [comment]
The `--giabreport` only works with the GIAB SVs for benchmarking. See [Using the GIAB Report](https://github.com/spiralgenetics/truvari/wiki/bench) for details.
